language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
sudo: required
services:
  - docker
env:
  - TASK=lint
  - TASK=test:geth
  - TASK=test:parity
  - TASK=coverage
before_script:
  - npm prune
script: "npm run $TASK"
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
after_script:
  - npm run cleanup:docker
