version: '2'
services:
    core:
        build: .
        image: aragon/core
        hostname: aragon-core
        ports:
         - "3000:3000"
        volumes:
        - ./docker_home:/root/
        - ./contracts:/usr/src/app/contracts
        - ./test:/usr/src/app/test
